[build]
    functions = "./netlify/functions"
    command = "yarn run build"
    publish = "build"
    port = "8080"

[dev]
    command = "svelte-kit dev"

[[_redirects]]
    from = '/api/*'
    to = '/.netlify/functions/:splat'
    status = 200